### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by cogmind** [cogmind/Filmvisarna#8]
```
Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at HTMLImageElement.nextRangeShows (shows.js:22)
    at HTMLElement.dispatch (jquery-3.6.0.min.js:2)
    at HTMLElement.v.handle (jquery-3.6.0.min.js:2)
```

Error in https://github.com/cogmind/Filmvisarna/blob/feature/shows/js/shows.js

Line 22:     this.shows.length            shows undefined

**Comment by cogmind** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Problem med visningar](https://trello.com/c/zvf37AAP/63-problem-med-visningar)

**Comment by Theodor-Bjornslatt** [comment]
Problem solved. Event handler needed a ".bind(this)" to reference the correct object.
